---
- name: Configure test servers
  hosts: all
  become: True
  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes

    - name: Install dependent packages
      apt:
        pkg:
        - tmux
        - vim
        - apt-transport-https
        - ca-certificates
        - curl
        - gnupg-agent
        - software-properties-common

    - name: Apt key for docker repo
      apt_key:
        url: https://download.docker.com/linux/debian/gpg
        state: present

    - name: Add the Docker repo
      apt_repository:
        repo: deb https://download.docker.com/linux/debian buster stable
        state: present

    - name: Install the docker engine
      apt:
        pkg:
        - docker-ce
        - docker-ce-cli
        - containerd.io
        update_cache: yes

    - name: Make sure docker is running
      service:
        state: started
        enabled: yes
        name: docker

    - name: Add vagrant user to docker group
      user:
        name: vagrant
        groups: docker
        append: yes
