---
- name: Configure test servers
  hosts: all
  become: True
  tasks:
    - name: Run the equivalent of "apt-get update"
      apt:
        update_cache: yes
    - name: Install a list of packages
      apt:
        pkg:
        - tmux
        - vim
